franklee26/appfolio-scheduleme

- app/controllers/tenants_controller.rb
- app/javascript/components/CustomNavbar.js
- app/views/tenants/show.html.erb
- config/routes.rb
- db/seeds.rb
1) Changed Tenant login route from "new" to "login"
2) Added route to tenant/login onto Navbar (Replaced the "Search" button)
3) Added show resource to tenant, allows you to "show" a tenant with a specific user id with localhost:3000/tenants/userid where user id = 1,2, or 3, depending on seeded data.
4) Edited seeded data to include sample emails for tenants
> Changed Tenant login route, added route to login onto navbar, added Show resource to tenant

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/calendar_controller.rb
- app/controllers/homepage_controller.rb
- app/controllers/landowners_controller.rb
- app/controllers/tenants_controller.rb
- app/javascript/components/CalendarIndex.js
- app/javascript/components/CustomNavbar.js
- app/javascript/components/Homepage.js
- app/javascript/components/UserSelection.js
- app/views/calendar/index.html.erb
- app/views/calendar/user_selection.html.erb
- app/views/homepage/index.html.erb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
AC:
* Integrated new Google API call to retrieve authorized user's name and email
* Built `user_type` view and controller action
* Built 'behind-the-scene' login/registration method that finds/creates a Tenant/Landowner object
* Built new auth routes for Tenant & Landowner (not very DRY but it works for now)
* Updated homepage view to display all registered users from database
* Moved Google API `clientOptions` into the global `application_controller`
* Added `Landowner` seed data
Notes:
* Added `pry` gem
> Integrate google login with rails models

- app/javascript/components/LandownerLandingPage.js
- app/javascript/components/VendorList.js
- app/javascript/components/VendorSearch.js
- test/models/vendor_test.rb
Users can now search vendors by name and occupation
> Added functionality to the vendor search

- app/controllers/tenants_controller.rb
- app/javascript/components/TenantProfilePage.js
- app/views/tenants/profile.html.erb
- config/routes.rb
1) Create tenant profile page. It only displays tenant's name and email right now. 
2) Modified "show" in tenant_controller to render a json of the passed in tenant id
3) Tenant ID is hard coded in profile.html.erb right now. 
- Try out at /tenant/profile
> added profile page for the tenant. 

- app/controllers/landowners_controller.rb
- app/controllers/tenants_controller.rb
- app/controllers/vendor_controller.rb
- app/javascript/components/LandownerProfilePage.js
- app/javascript/components/TenantProfilePage.js
- app/javascript/components/VendorProfilePage.js
- app/views/landowners/profile.html.erb
- app/views/tenants/profile.html.erb
- app/views/vendor/profile.html.erb
- config/routes.rb
1) Created a profile page for vendor at localhost:3000/vendors/profile
2) Created a profile page for landowners at localhost:3000/landowner/profile
> Weiyee goh landowner and vendor profile page

- app/javascript/components/TenantProfilePage.js
- db/migrate/20200120060020_add_address_to_tenants.rb
- db/schema.rb
- db/seeds.rb
Tenant table should have fields to store the tenant's address, so I've added these fields to the table. I've also added these fields to the tenant profile page and made the tenant profile page fields editable so the user can change their address or email or etc.
> Added Address fields to the tenant

- app/controllers/landowners_controller.rb
- app/javascript/components/CalendarIndex.js
- config/routes.rb
* Rewrote `CalendarIndex.js` with hooks (for readability)
* Added DELETE route that removes a tenant from a landowner
* Added delete functionality that uses DELETE route specified above
* Removed redundant `landownerTenantsResponse` state and removed redundant api at `/landowner/tenants/:landowner_id`
* GET landowner now includes its tenants
* Cleaned up code a bit more
> More landowner <--> tenant associations + cleanup

- app/controllers/sessions_controller.rb
- app/javascript/components/CustomNavbar.js
- config/routes.rb
Added the calendar/login route to the login button.
Added a logout button, the logout button invokes the sessions#destroy action which will clear the global sessions variable of any users and user types, followed by a redirect to the homepage
> changed login button route, added logout button

- app/controllers/tenants_controller.rb
- app/javascript/components/TenantProfilePage.js
- config/routes.rb
Made a patch request to update a tenant based on the new information the user enters in the tenant profile page.
> Made patch request for tenant profile update

- app/controllers/application_controller.rb
- app/controllers/calendar_controller.rb
- went into refreshToken() function in application_controller and updated the access/refresh token for every user of the same email as the one passed in
- went into calendar_controller callback to also update the access/refresh token for every user of the same email as the one passed in
> fixed issue where same emails with different users will break the code

- app/views/about/index.html.erb
Added a homepage and a route that allows you to sign up and login.
> New Homepage

- app/views/about/index.html.erb
> Fixing the sign up button

- app/javascript/components/JobNew.js
- yarn.lock
added banner to job submission
> added banner to job submission

- app/controllers/landowners_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/tenants_controller.rb
- app/controllers/vendors_controller.rb
- app/javascript/components/CustomNavbar.js
- app/views/landowners/profile.html.erb
- app/views/sessions/profile_page.html.erb
- app/views/tenants/profile.html.erb
- app/views/vendors/profile.html.erb
- config/routes.rb
Cleaned up navbar so logout only shows up when you're already logged in. Also login only shows up on navbar when you're not logged in. Added a get api call for session. Profile is no longer hardcoded so you can now do things like set your vendor occupation through the profile.
> Functionality to add vendor occupation and navbar cleanup

- app/controllers/calendar_controller.rb
- app/javascript/components/CalendarIndex.js
- app/javascript/components/CalendarSubmission.js
- app/javascript/components/Events.js
- app/javascript/components/JobNew.js
- app/javascript/components/TenantProfilePage.js
- app/views/calendar/calendar_submission.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/routes.rb
* Decluttered Tenant landing page: removed calendar selection from tenant landing page
* Moved calendar selection to a separate view for better ux
* Added a progressive workflow: tenant submits job request, then selects calendar, then submits time
* Removed some alert banners and replaced with a nicer bootstrap model
* Added fancy spinner for loading displays
* Small UI adjustments (eg. added loading bar for ease and changed colours for consistency)
> Job submission v5

- app/javascript/components/CalendarIndex.js
- Changed Card to Border Cards
- Added Buttons within each card for action, instead of having the entire button as an action.
- Made coloring more consistent.
> Redesigned Landowner Landing Page

- app/controllers/tenants_controller.rb
- app/javascript/components/CalendarIndex.js
- app/javascript/components/Events.js
- app/javascript/components/JobNew.js
- package.json
- yarn.lock
* Added cards for events page
* event cards now display vendor name and corresponding rating
* added star ratings to event cards and replaced job review rating
* small fixes
> Updated events

- app/controllers/vendors_controller.rb
- app/javascript/components/CalendarIndex.js
- app/javascript/components/VendorDisplay.js
- app/javascript/components/VendorSearch.js
- app/views/vendors/display.html.erb
- config/routes.rb
* Removed calendar selection for landowners
* Changed all landowner alerts to bootstrap modals
* Added stars to vendor search, hover information and spinner
* Added a `VendorDisplay` component for vendor search: advertises ratings and previous reviews
> UX updates

- app/javascript/components/CalendarIndex.js
- app/javascript/components/CalendarSubmission.js
- app/javascript/components/JobNew.js
Fixed the text for a few banners and made capitalization more consistent.
Added banner to Tenant Home.
> UI/UX changes + banner change for Tenant Home

- app/javascript/components/VendorDisplay.js
Made cards horizontal and modified headers.
> Revamped Review UI

- app/controllers/calendar_controller.rb
- app/controllers/vendors_controller.rb
- app/javascript/components/CalendarIndex.js
- app/javascript/components/CalendarModals.js
- app/javascript/components/Events.js
- app/javascript/components/LandownerProfilePage.js
- app/javascript/components/TenantProfilePage.js
- app/javascript/components/VendorCalendar.js
- app/javascript/components/VendorProfilePage.js
- app/views/calendar/index.html.erb
- package.json
- yarn.lock
* Added Google Calendar snippet to Vendors page (different module than the one @WeiyeeGoh used)
* Added basic direction cycling for vendors
* Updated vendors UI to match rest of the webapp
* Cleaned up CalendarIndex by adding separate VendorCalendar rendering and CalendarModal (used ReactRouter)
NOTE: You're going to need to add a `google_maps_key` to your ENV file
> Google Maps

- app/javascript/components/CalendarIndex.js
- app/javascript/components/CustomNavbar.js
- app/javascript/components/VendorCalendar.js
* Added tabs to tenants and vendors
* Added logo to navbar
* Made profile pic smaller
> Tenant and Vendor tabs

- app/javascript/components/CustomNavbar.js
> reduced width of navbar

- app/javascript/components/CalendarSubmission.js
- app/javascript/components/Events.js
- app/javascript/components/JobNew.js
- app/javascript/components/VendorSelection.js
> progressbar no animation

- app/javascript/components/Events.js
- app/javascript/components/JobNew.js
- app/javascript/components/VendorSelection.js
Added profile pictures to vendor selection page in the job submission process and on the summary card in the events page.
> added profile pics to vendor selection

- app/javascript/components/CalendarIndex.js
- app/javascript/components/CalendarModals.js
- app/javascript/components/CalendarProfile.js
- app/javascript/components/VendorCalendar.js
* Added small tenant profile for the profile tabs
* Replaced alert with modal for "complete all jobs" on Vendor side
* Added spinners for CalendarIndex
> Tenant profile

- app/controllers/calendar_controller.rb
- fixed some bugs
- updated 8 to 7 for time zone diff
> added fix for scheduler

- app/javascript/components/VendorSearch.js
added scrolling to vendor search
> added scrolling to vendor list

- app/javascript/components/VendorCalendar.js
* Added jumbotron for no upcoming jobs
> Vendor stuff
